sudo: required
services:
    - docker

script:
  - docker build -t diabid/node .
  - docker images diabid/node

before_deploy:
  - docker login -u diabid -p Docker@2020

deploy:
  provider: script
  script: docker push diabid/node
  on:
    branch: master
